version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: groops-postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: groops
    ports:
      - "5432:5432"
  nginx:
    image: nginx:1.25.2-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
    network_mode: "host"

volumes:
  pgdata:
    name: groops-pgdata
