version: "3.8"

services:
  groops-backend:
    image: groops-backend:${VERSION:-latest}
    container_name: groops-backend
    restart: always
    entrypoint: "java -jar -Dspring.profiles.active=dev app.jar"
    environment:
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - logs:/app/logs
    build:
      context: "."
    network_mode: "host"
    ports:
      - "8085:8085"
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    container_name: groops-postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: groops
    ports:
      - "5432:5432"
  nginx:
    image: nginx:1.25.2-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-conf/dev/nginx.conf:/etc/nginx/nginx.conf
    network_mode: "host"
volumes:
  pgdata:
    name: groops-pgdata
  logs:
    name: groops-logs