version: "3.8"

services:
  groops-backend:
    image: groops-backend:${VERSION:-latest}
    container_name: groops-backend
    restart: always
    entrypoint: "java -jar -Dspring.profiles.active=prod app.jar"
    environment:
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - logs:/app/logs
    build:
      context: "."
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    networks:
      appnet:
        ipv4_address: 172.24.2.2
  postgres:
    image: postgres:14-alpine
    container_name: groops-postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: groops
    ports:
      - "5432:5432"
    networks:
      appnet:
        ipv4_address: 172.24.2.4
  nginx:
    image: nginx:1.25.2-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "443:443"
#      - "80:80"
    volumes:
      - ./nginx-conf/prod/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/prod-test-cert/test.com.crt:/etc/nginx/ssl/test.com.crt
      - ./nginx-conf/prod-test-cert/test.com.key:/etc/nginx/ssl/test.com.key
    networks:
      appnet:
        ipv4_address: 172.24.2.6
networks:
  appnet:
    name: groops_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/16"
volumes:
  pgdata:
    name: groops-pgdata
  logs:
    name: groops-logs