version: "3.3"

services:
  postgres:
    image: postgres:14-alpine
    container_name: groops-postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: groops
    ports:
      - "5432:5432"
volumes:
  pgdata:
    name: groops-pgdata
