package hr.tvz.groops.exception.csv.testDeviceLogs.enums;

public enum TDLCSVProcessingExceptionEnum {
    INVALID_BOOLEAN, INVALID_DATE, INVALID_DATE_TIME, INVALID_INTEGER, INVALID_VALUE,
    NO_KEY, NON_EXISTING_KEY, NO_VALUES, CSV_PROCESSING, PARSE, CSV_VALIDATION, IO, OTHER,
    MISSING_DATE_AND_DATETIME, MISSING_SERIAL, NO_ZIPATESTER_APP_VERSION, MISSING_LAST_MODIFIED_DATE,
    LAST_MODIFIED_DATE_DATE_OF_TEST_MISMATCH
}
