server.port=8085
server.servlet.contextPath=/groops/
#spring.profiles.active=dev
logging.level.org.springframework.web=TRACE
# these messages show validation errors in HTTP response
server.error.include-message=always
server.error.include-binding-errors=always

app.version.file=@project.basedir@/VERSION

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/groops
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true

# this allows logging of sql statements in the console
spring.jpa.show-sql=true
# The values create, create-drop, validate, and update basically influence how
# the schema tool management will manipulate the database schema at startup.
spring.jpa.hibernate.ddl-auto=none
logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#flyway config
spring.flyway.url=jdbc:postgresql://localhost:5432/groops
spring.flyway.schemas=public
spring.flyway.user=postgres
spring.flyway.password=password
spring.flyway.baseline-on-migrate = true
spring.flyway.locations=classpath:/db/migration

#jwt
groops.jwt.tokenPrefix=Bearer 
groops.jwt.tokenExpirationAfterSeconds=86400
groops.jwt.issuer=groops.com
groops.jwt.header-name=Authorization

groops.jwt.app.issuer=${groops.jwt.issuer}
groops.jwt.app.tokenPrefix=${groops.jwt.tokenPrefix}
groops.jwt.app.tokenExpirationAfterSeconds=${groops.jwt.tokenExpirationAfterSeconds}
groops.jwt.app.secret-key-base64=aukHm7g3GMvfnqEEtixgeEzIDm8LJH1JChmz4XFHysA=
groops.jwt.app.header-name=${groops.jwt.header-name}

groops.jwt.mail.create.issuer=${groops.jwt.issuer}
groops.jwt.mail.create.tokenPrefix=${groops.jwt.tokenPrefix}
groops.jwt.mail.create.tokenExpirationAfterSeconds=${groops.jwt.tokenExpirationAfterSeconds}
groops.jwt.mail.create.secret-key-base64=rmhG!$hJs+Z5j83a)b(4!DJyXuS35pWRuRBLNc&B7n(pLbB$RJXn7Q)ecV(PG%&B
groops.jwt.mail.create.header-name=authorization-x-mail-create

groops.jwt.mail.change.issuer=${groops.jwt.issuer}
groops.jwt.mail.change.tokenPrefix=${groops.jwt.tokenPrefix}
groops.jwt.mail.change.tokenExpirationAfterSeconds=${groops.jwt.tokenExpirationAfterSeconds}
groops.jwt.mail.change.secret-key-base64=!UQmaUpB6@^rsvb6(YhWG)EYeU^Gb7G9xyFvS8Yw#QWrIvcgQ#w#@)H2qc(UG5NK
groops.jwt.mail.change.header-name=authorization-x-mail-change

groops.jwt.password.change.issuer=${groops.jwt.issuer}
groops.jwt.password.change.tokenPrefix=${groops.jwt.tokenPrefix}
groops.jwt.password.change.tokenExpirationAfterSeconds=${groops.jwt.tokenExpirationAfterSeconds}
groops.jwt.password.change.secret-key-base64=SfRBy5mtjcSVHqZt8N&y7XCIEme@T*!re!rPcvk7yeVR3q@rjxf9JhdgzF@Ptsc9
groops.jwt.password.change.header-name=authorization-x-password-change

#server file size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#jdbc-template log
logging.level.org.springframework.jdbc.core=DEBUG
#rest-teplate
logging.level.org.springframework.web.client.RestTemplate=TRACE

#url
groops.hostname.base.default = localhost:${server.port}/

# Logger options
logging.file.path=logs
groops.logging.placeholder.username=loggedInUser
logging.pattern.console = %clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %X{${groops.logging.placeholder.username}} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
logging.pattern.file = %d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSSXXX}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- %X{${groops.logging.placeholder.username}} [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}

# actuator
management.endpoints.web.exposure.include=*
management.endpoint.loggers.enabled=true

#mail
spring.mail.templates.path=templates/mail/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mislav.srecec3@gmail.com
spring.mail.password=onntfhppfyhhbpeb
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.debug=true

groops.mail.scheduler = true
groops.mail.expires.days = 10